pipeline {
  agent any

  stages {
    stage('Run in Docker') {
      steps {
        sh 'docker pull node:16-alpine' // Fix: again for windows
        sh 'docker run --rm node:16-alpine node --version' // Fix: again for windows
      }
    }
  }
}
