pipeline {
  agent any

  stages {
    stage('Run in Docker') {
      steps {
        script {
          bat 'docker pull node:16-alpine' // Fix: for windows
          bat 'docker run --rm node:16-alpine node --version' // Fix: for windows
        }
      }
    }
  }
}
